export const PREDEFINED_SKILLS: string[] = [
  "Statistics",
  "Mathematics",
  "Quantitative Analysis",
  "Numerical Methods",
  "R programming language",
  "Python for Data Science",
  "MATLAB",
  "SQL",
  "MySQL",
  "MongoDB",
  "BigQuery",
  "Data Extraction",
  "Data Modeling",
  "Data Cleansing",
  "Data Migration",
  "Data Governance",
  "Big Data",
  "Data Spooling",
  "Data Warehousing",
  "ETL",
  "Excel",
  "Excel VBA",
  "Hadoop",
  "Jupyter Notebooks",
  "MapReduce",
  "Matplotlib",
  "PyTorch",
  "Power BI",
  "Tableau",
  "Pandas",
  "LLM Evaluation",
  "Data Annotation",
  "Prompt Engineering",
  "RLHF",
  "Fact-Checking",
  "Modern Standard Arabic",
  "Egyptian Arabic",
  "Maghrebi Arabic",
  "Saudi Arabic",
  "Emirati Arabic",
  "French",
  "English",
  "Linguistics",
  "Translation",
  "Organic Chemistry",
  "WordPress",
  "SEO",
  "Video Editing",
  "Adobe After Effects",
  "JSON-LD",
];